In [4]:
import numpy as np

In [5]:
data = np.random.randn(4, 3)

In [6]:
data

array([[-0.52441682, -0.38363948, -0.0043266 ],
       [-1.8079823 ,  1.60853076,  0.58324447],
       [ 1.05644224,  0.00542717,  1.90435112],
       [-0.97528463, -0.3325661 ,  1.91733122]])

In [7]:
data*10

array([[ -5.24416821,  -3.83639477,  -0.04326596],
       [-18.07982296,  16.08530759,   5.83244469],
       [ 10.56442236,   0.05427169,  19.04351123],
       [ -9.75284628,  -3.32566097,  19.17331221]])

In [8]:
data + data

array([[-1.04883364, -0.76727895, -0.00865319],
       [-3.61596459,  3.21706152,  1.16648894],
       [ 2.11288447,  0.01085434,  3.80870225],
       [-1.95056926, -0.66513219,  3.83466244]])

In [9]:
data.shape

(4, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
data1

[6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
arr1.ndim

1

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2.ndim

2

In [19]:
data3 = np.empty((2,2))

In [20]:
data3

array([[6. , 7.5],
       [8. , 1. ]])

In [21]:
float_arr = arr2.astype(np.float64)

In [22]:
float_arr.dtype

dtype('float64')

In [23]:
float_arr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe','Joe'])

In [40]:
data = np.random.randn(8, 4)

In [41]:
data[names == 'Bob']

array([[ 0.96257348,  0.53114704, -0.80097186,  1.91311821],
       [-0.18306143,  1.28671162, -0.62155733, -1.45478053]])

In [42]:
data[names == "Joe"]

array([[ 0.33334361, -0.73001431,  0.29225529,  1.56797448],
       [ 0.10955231,  0.3219484 , -0.20773399, -2.03813923],
       [-0.70803365, -0.18657494,  1.11342441,  1.26434242],
       [ 1.11747174, -0.06413958, -1.01772288, -0.29005823]])